#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/389b7c96-0bdd-4bbc-9cbf-0ba74f2a04d3 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudRelativeHumidity soil_water;
  bool wateringNow;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/
int OP_PIN=0;
int threshold=50;
#include "thingProperties.h"
void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(115200);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  pinMode(OP_PIN,OUTPUT); //output pin for relay board, this will sent signal to the relay
  pinMode(A0,INPUT); //input pin coming from soil sensor
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  soil_water=100 - (analogRead(A0)/10);
  Serial.print("Current Water Level:"+soil_water);
  if(wateringNow){
    Serial.print("Force Watering\n");
    digitalWrite(OP_PIN,LOW);
  }
  else{
    if(soil_water<threshold){
      Serial.print("Watering Automatically\n");
      digitalWrite(OP_PIN,LOW);
    }
    else{
      Serial.print("Not Watering\n");
      digitalWrite(OP_PIN,HIGH);
    }
  }
}

/*
  Since SoilWater is READ_WRITE variable, onSoilWaterChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onSoilWaterChange()  {
  // Add your code here to act upon SoilWater change
}
/*
  Since WateringNow is READ_WRITE variable, onWateringNowChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onWateringNowChange()  {
  // Add your code here to act upon WateringNow change
  
}
